export enum Abilities {
  Logout = 1,
  Change_Password = 5,
  Get_User_ChechIns = 6,
  Get_All_Other_Users = 7,
  Get_Holidays = 9,
  Get_Holiday = 10,
  Add_Holiday = 11,
  Delete_Holiday = 12,
  Update_Holiday = 13,
  Get_Current_User_Vacations = 14,
  Get_All_Vacations = 15,
  Get_User_Vacations = 16,
  Change_Vacation_Status = 17,
  Delete_Vacation = 18,
  Add_Vacation = 19,
  Get_Current_User_CheckIns = 20,
  User_CheckIns_Calculations = 21,
  Current_User_CheckIns_Calculations = 22,
  Get_Roles = 23,
  Get_Role = 24,
  Add_Role = 25,
  Delete_Role = 26,
  Update_Role = 27
}